import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'rw' | 'fr' | 'sw';

const translations: Record<Language, Record<string, string>> = {
  en: {
    hero_title: 'Find trusted work. Hire trusted people.',
    hero_subtitle: 'LINEKORA is Africa\'s most secure marketplace connecting verified workers with vetted employers.',
    find_jobs: 'Find Jobs',
    hire_workers: 'Hire Workers',
    about: 'About',
    pricing: 'Pricing',
    contact: 'Contact',
    safety: 'Safety',
    login: 'Log in',
    join: 'Join LINEKORA',
    dashboard: 'Dashboard',
    post_job: 'Post Job',
    post_task: 'Post Task',
    browse_workers: 'Browse Workers',
    browse_jobs: 'Browse Jobs',
    profile: 'My Profile',
    applications: 'Applications',
    messages: 'Messages',
    verification: 'Verification',
    reviews: 'Reviews',
    wallet: 'Wallet',
    settings: 'Settings',
    logout: 'Log Out',
    active_jobs: 'Active jobs',
    verified_workers: 'Verified workers',
    verified_companies: 'Verified companies',
    completed_hires: 'Completed hires',
    manage_jobs: 'Manage Jobs',
    applicants: 'Applicants',
    payments: 'Payments',
    analytics: 'Analytics',
    public_home: 'Public Homepage',
    trust_score: 'Trust Score',
    milestone_blockage_title: 'Active Milestone Blockage',
    milestone_blockage_platform: 'LINEKORA Platform Quality Guarantee',
    milestone_blockage_desc: 'Platform safety directives require clients to first update, evaluate, or approve outstanding active assignments and leave ratings/reviews before posting more new listings.',
    milestone_resolve_hint: 'Resolve instantly on your Dashboard:',
    milestone_resolve_desc: 'Browse down your workspace, select the active task submitted by your worker, and click "Approve & Complete" to release escrow holdings and rate the performance.',
    milestone_go_dashboard: 'Go to Workspace Dashboard',
    corporate_blockage_title: 'Corporate Milestone Blockage',
    corporate_blockage_platform: 'LINEKORA Corporate Integrity Guarantee',
    corporate_blockage_desc: 'Platform safety directives require corporate clients to first update, evaluate, or approve outstanding active assignments and leave ratings/reviews before posting more new listings.',
    corporate_resolve_hint: 'Resolve instantly on your Dashboard:',
    corporate_resolve_desc: 'Browse down your corporate workspace, select the active contract submitted by your worker, and click "Approve & Complete" to release escrow holdings and rate the performance.',
    corporate_go_dashboard: 'Go to Corporate Dashboard',
    active_contracts_title: 'Active Contracts & Milestone Handovers',
    active_contracts_desc: 'Approve finished milestones, request progress updates, or flag issues immediately.',
    contract_active: 'Active Contract',
    completion_requested: 'Completion Requested',
    in_progress_correction: 'In Progress Correction',
    arbitration_dispute: 'Arbitration Dispute',
    finished_approved: 'Finished & Approved',
    flagged_untrusted: 'Flagged Untrusted',
    approve_complete: 'Approve & Complete',
    need_adjustment: 'Need Adjustment',
    dispute: 'Dispute',
    mark_untrusted: 'Mark Untrusted',
    all_contracts_settled: 'All Contracts Fully Settled',
    no_outstanding: 'No outstanding handovers or pending completion flags outstanding.',
    file_worker_reputation: 'File Worker Reputation',
    masterclass_standard: 'MasterClass Standard (5/5)',
    highly_commended: 'Highly Commended (4/5)',
    standard_alignment: 'Standard Alignment (3/5)',
    needs_revision: 'Needs Revision (2/5)',
    flagged_poor: 'Flagged Poor Work (1/5)',
    submit_release_funds: 'Submit & Release Funds',
    disputed_milestone: 'Disputed milestone',
    milestone_dispute_log: 'Milestone dispute requested. Initial arbitration reviews have commenced.',
    milestone_returned: 'Milestone Returned',
    perfect_execution: 'Perfect execution!',
    contract_approved: 'Contract Approved & Dispatched',
    milestone_approved_escrow: 'Milestone Approved! Escrows dispatched and rating recorded safely.',
    escalation_warning: 'Automatic 3-Day Overdue Escrow Escalation',
    escalation_desc: 'This completion was submitted 3 days ago. Platform safeguards require prompt review.',
    milestone_secure_escrow: 'LINEKORA Guard Secure Escrow',
    milestone_secure_desc: 'This job uses our milestone security guarantees. The salary is held in a trust vault prior to milestones being finished to ensure honest payout.',
    completion_requested_blocked: 'Completion Requested & Blocked',
    disputed_admin_audit: 'Disputed: Under LINEKORA Admin Audit',
    flagged_penalty: 'Flagged: Not Trusted Penalty',
    request_completion: 'Request Completion',
  },
  rw: {
    hero_title: 'Gana akazi kizewe. Nyereka abakozi bizewe.',
    hero_subtitle: 'LINEKORA niryo soko ryizewe cyane muri Afrika rihuza abakozi bagenzuwe n\'abakoresha bizewe.',
    find_jobs: 'Shaka Akazi',
    hire_workers: 'Shaka Abakozi',
    about: 'Turi Ba Nde',
    pricing: 'Ibiciro',
    contact: 'Twandikire',
    safety: 'Umutekano',
    login: 'Injira',
    join: 'Fatanya na LINEKORA',
    dashboard: 'Imbonerahamwe',
    post_job: 'Shyiraho Akazi',
    post_task: 'Shyiraho Igikorwa',
    browse_workers: 'Shaka Abakozi',
    browse_jobs: 'Shaka Imirimo',
    profile: 'Umwirondoro',
    applications: 'Gusaba Akazi',
    messages: 'Ubutumwa',
    verification: 'Kugenzura',
    reviews: 'Ibitekerezo',
    wallet: 'Ububiko bw\'Amafaranga',
    settings: 'Igenamiterere',
    logout: 'Sohoka',
    active_jobs: 'Imirimo ihari',
    verified_workers: 'Abakozi bagenzuwe',
    verified_companies: 'Ibigo byagenzuwe',
    completed_hires: 'Abahawe akazi',
    manage_jobs: 'Cunga Imirimo',
    applicants: 'Abasaba Akazi',
    payments: 'Kwishura',
    analytics: 'Ibigaragazwa',
    public_home: 'Urubuga Nyamukuru',
    trust_score: 'Amanota y\'ikinyabupfura',
    milestone_blockage_title: 'Inzitizi ku ntambwe y\'Ibikorwa',
    milestone_blockage_platform: 'Umwugaro w\'Ubwiza bw\'Urugendo rwa LINEKORA',
    milestone_blockage_desc: 'Amategeko y\'umutekano y\'urugendo yifuza ko abakoresha bategura, bagasuzuma cyangwa bakemura ibikorwa bihari mbere yo gutanga amakuru ashya.',
    milestone_resolve_hint: 'Kemura byihuse kuri Imbonerahamwe yawe:',
    milestone_resolve_desc: 'Rondera aho ukorera, hitamwo ikikorwa umukoresha wawe yohereje, ukande "Emeza & Kurangiza" kugira ngo uburenganzira bw\'amafaranga buhagariwe.',
    milestone_go_dashboard: 'Kujya ku Imbonerahamwe',
    corporate_blockage_title: 'Ubu bwobo bw\'Ibikorwa by\'Ibigo',
    corporate_blockage_platform: 'Ubwiza bw\'Ibigo by\'Urugendo rwa LINEKORA',
    corporate_blockage_desc: 'Amategeko y\'umutekano y\'urugendo yifuza ko ibigo bigize ikorwa bigitegura, bisuzume cyangwa bikemure ibikorwa bihari mbere yo gutanga amakuru ashya.',
    corporate_resolve_hint: 'Kemura byihuse kuri Imbonerahamwe yawe:',
    corporate_resolve_desc: 'Rondera aho ukorera, hitamwo ikikorwa umukoresha wawe yohereje, ukande "Emeza & Kurangiza" kugira ngo uburenganzira bw\'amafaranga buhagariwe.',
    corporate_go_dashboard: 'Kujya ku Imbonerahamwe y\'Igigo',
    active_contracts_title: 'Amasezerano Ahari & Ibikorwa by\'Ubusabane',
    active_contracts_desc: 'Emeza ibikorwa byarangiye, saba amakuru y\'ibikorwa, cyangwawereke ikibazo.',
    contract_active: 'Amasezerano Ahari',
    completion_requested: 'Ukurangiza Byasabwe',
    in_progress_correction: 'Gusubiramo mu Bikorwa',
    arbitration_dispute: 'Ibaza ryo mu Buryo',
    finished_approved: 'Byarangiye & Byemewe',
    flagged_untrusted: 'Wagaragajwe Ntiwizewe',
    approve_complete: 'Emeza & Kurangiza',
    need_adjustment: 'Birasabwa Gukosorwa',
    dispute: 'Ibaza',
    mark_untrusted: 'Shyira Ntiwizewe',
    all_contracts_settled: 'Amasezerano Yose Yarangiye',
    no_outstanding: 'Nta bikorwa bihari cyangwa ibyo gukemura biriho.',
    file_worker_reputation: 'Andika Uburambe bw\'Umukozi',
    masterclass_standard: 'Urwego rwo Hejuru (5/5)',
    highly_commended: 'Birabereye (4/5)',
    standard_alignment: 'Urwego rusanzwe (3/5)',
    needs_revision: 'Birasabwa Gukosorwa (2/5)',
    flagged_poor: 'Umukozi Ntibi (1/5)',
    submit_release_funds: 'Ohereza & Uhagarike Amafaranga',
    disputed_milestone: 'Igikorwa kiri mu ibaza',
    milestone_dispute_log: 'Ibaza r\'igikorwa ryasabwe. Ibinyejana by\'iburanisho byatangiye.',
    milestone_returned: 'Igikorwa Cyagarutswemo',
    perfect_execution: 'Umukozi wakoze neza!',
    contract_approved: 'Amasezerano Yemewe & Yoherejwe',
    milestone_approved_escrow: 'Igikorwa Cyemewe! Amafaranga yoherejwe n\'ibyiyumviro byabitswe.',
    escalation_warning: 'Kwiyongera kw\'Amazamu y\'Iminsi 3',
    escalation_desc: 'Icyo kirango cyoherejwe iminsi 3 ishize. Amategeko y\'umutekano asaba ko ikibazo gikemurwa vuba.',
    milestone_secure_escrow: 'Umuco w\'Umutungo wa LINEKORA',
    milestone_secure_desc: 'Iyi akazi ikoresha amasezerano y\'umutekano y\'ibikorwa. Amafaranga arindwa mu bwato mbere yo kurangiza ibikorwa kugira ngo ibihembwe by\'ukuri.',
    completion_requested_blocked: 'Ukurangiza Byasabwe & Bisobetse',
    disputed_admin_audit: 'Biri mu Ibaza: Biriko birasuzumwa n\'Abashinzwe',
    flagged_penalty: 'Wagaragajwe: Igiciro cy\'Ubu bwobo',
    request_completion: 'Saba Kurangiza',
  },
  fr: {
    hero_title: 'Trouvez un travail de confiance. Embauchez des personnes de confiance.',
    hero_subtitle: 'LINEKORA est le marché le plus sécurisé d\'Afrique reliant des travailleurs vérifiés à des employeurs agréés.',
    find_jobs: 'Trouver des Emplois',
    hire_workers: 'Embaucher des Travailleurs',
    about: 'À Propos',
    pricing: 'Tarifs',
    contact: 'Contact',
    safety: 'Sécurité',
    login: 'Se connecter',
    join: 'Rejoindre LINEKORA',
    dashboard: 'Tableau de bord',
    post_job: 'Publier un emploi',
    post_task: 'Publier une tâche',
    browse_workers: 'Parcourir les travailleurs',
    browse_jobs: 'Parcourir les emplois',
    profile: 'Mon profil',
    applications: 'Candidatures',
    messages: 'Messages',
    verification: 'Vérification',
    reviews: 'Avis',
    wallet: 'Portefeuille',
    settings: 'Paramètres',
    logout: 'Se déconnecter',
    active_jobs: 'Emplois actifs',
    verified_workers: 'Travailleurs vérifiés',
    verified_companies: 'Entreprises vérifiées',
    completed_hires: 'Embauches terminées',
    manage_jobs: 'Gérer les emplois',
    applicants: 'Candidats',
    payments: 'Paiements',
    analytics: 'Analyses',
    public_home: 'Accueil Public',
    trust_score: 'Score de confiance',
    milestone_blockage_title: 'Blocage de Jalons Actif',
    milestone_blockage_platform: 'Garantie de Qualité de la Plateforme LINEKORA',
    milestone_blockage_desc: 'Les directives de sécurité de la plateforme exigent que les clients mettent à jour, évaluent ou approuvent les tâches en cours avant de publier de nouvelles annonces.',
    milestone_resolve_hint: 'Résolvez instantanément sur votre tableau de bord :',
    milestone_resolve_desc: 'Parcourez votre espace de travail, sélectionnez la tâche active soumise par votre travailleur et cliquez sur "Approuver et Terminer" pour libérer les fonds en séquestre.',
    milestone_go_dashboard: 'Aller au Tableau de Bord',
    corporate_blockage_title: 'Blocage de Jalons d\'Entreprise',
    corporate_blockage_platform: 'Garantie d\'Intégrité Entreprise LINEKORA',
    corporate_blockage_desc: 'Les directives de sécurité de la plateforme exigent que les entreprises mettent à jour, évaluent ou approuvent les tâches en cours avant de publier de nouvelles annonces.',
    corporate_resolve_hint: 'Résolvez instantanément sur votre tableau de bord :',
    corporate_resolve_desc: 'Parcourez votre espace d\'entreprise, sélectionnez le contrat actif soumis par votre travailleur et cliquez sur "Approuver et Terminer".',
    corporate_go_dashboard: 'Aller au Tableau de Bord Entreprise',
    active_contracts_title: 'Contrats Actifs et Transferts de Jalons',
    active_contracts_desc: 'Approuvez les jalons terminés, demandez des mises à jour ou signalez des problèmes immédiatement.',
    contract_active: 'Contrat Actif',
    completion_requested: 'Achèvement Demandé',
    in_progress_correction: 'Correction en Cours',
    arbitration_dispute: 'Litige d\'Arbitrage',
    finished_approved: 'Terminé et Approuvé',
    flagged_untrusted: 'Signalé Non Fiable',
    approve_complete: 'Approuver et Terminer',
    need_adjustment: 'Ajustement Nécessaire',
    dispute: 'Litige',
    mark_untrusted: 'Marquer Non Fiable',
    all_contracts_settled: 'Tous les Contrats Régularisés',
    no_outstanding: 'Aucun transfert en attente ou drapeau de complétion en suspens.',
    file_worker_reputation: 'Déposer la Réputation du Travailleur',
    masterclass_standard: 'Standard MasterClass (5/5)',
    highly_commended: 'Hautement Recommandé (4/5)',
    standard_alignment: 'Alignement Standard (3/5)',
    needs_revision: 'Nécessite une Révision (2/5)',
    flagged_poor: 'Mauvais Travail Signalé (1/5)',
    submit_release_funds: 'Soumettre et Libérer les Fonds',
    disputed_milestone: 'Jalon en litige',
    milestone_dispute_log: 'Litige de jalon demandé. Les examens d\'arbitrage initiaux ont commencé.',
    milestone_returned: 'Jalon Retourné',
    perfect_execution: 'Exécution parfaite !',
    contract_approved: 'Contrat Approuvé et Envoyé',
    milestone_approved_escrow: 'Jalon Approuvé ! Les fonds en séquestre ont été libérés et l\'évaluation enregistrée.',
    escalation_warning: 'Escalade Automatique de 3 Jours de Retard',
    escalation_desc: 'Cet achèvement a été soumis il y a 3 jours. Les sauvegardes de la plateforme exigent un examen rapide.',
    milestone_secure_escrow: 'Séquestre Sécurisé LINEKORA',
    milestone_secure_desc: 'Ce poste utilise nos garanties de sécurité de jalons. Le salaire est détenu dans un coffre-fort avant l\'achèvement des jalons.',
    completion_requested_blocked: 'Achèvement Demandé et Bloqué',
    disputed_admin_audit: 'En Litige : Sous Audit Admin LINEKORA',
    flagged_penalty: 'Signalé : Pénalité Non Fiable',
    request_completion: 'Demander l\'Achèvement',
  },
  sw: {
    hero_title: 'Pata kazi ya kuaminika. Ajiri watu wa kuaminika.',
    hero_subtitle: 'LINEKORA ni soko salama zaidi barani Afrika linalounganisha wafanyakazi waliothibitishwa na waajiri wanaoaminika.',
    find_jobs: 'Tafuta Kazi',
    hire_workers: 'Ajiri Wafanyakazi',
    about: 'Kuhusu Sisi',
    pricing: 'Bei',
    contact: 'Wasiliana Nasi',
    safety: 'Usalama',
    login: 'Ingia',
    join: 'Jiunge na LINEKORA',
    dashboard: 'Dashibodi',
    post_job: 'Tuma Kazi',
    post_task: 'Tuma Kazi Ndogo',
    browse_workers: 'Tafuta Wafanyakazi',
    browse_jobs: 'Tafuta Kazi zilizopo',
    profile: 'Wasifu Wangu',
    applications: 'Maombi ya Kazi',
    messages: 'Ujumbe',
    verification: 'Uthibitishaji',
    reviews: 'Mapitio',
    wallet: 'Mkoba wa Pesa',
    settings: 'Mipangilio',
    logout: 'Ondoka',
    active_jobs: 'Kazi zinazoendelea',
    verified_workers: 'Wafanyakazi waliothibitishwa',
    verified_companies: 'Kampuni zilizothibitishwa',
    completed_hires: 'Kazi zilizokamilika',
    manage_jobs: 'Simamia Kazi',
    applicants: 'Waombaji',
    payments: 'Malipo',
    analytics: 'Uchambuzi',
    public_home: 'Ukurasa wa Kwanza',
    trust_score: 'Alama ya Uaminifu',
    milestone_blockage_title: 'Zuio la Hatua za Kazi',
    milestone_blockage_platform: 'Dhamana ya Ubora ya Jukwaa la LINEKORA',
    milestone_blockage_desc: 'Maelekezo ya usalama ya jukwaa yanahitaji wateja kusasisha, kutathmini au kuthibitisha kazi zilizopo kabla ya kuchapisha orodha mpya.',
    milestone_resolve_hint: 'Tatua mara moja kwenye Dashibodi yako:',
    milestone_resolve_desc: 'Vinjari sehemu yako ya kazi, chagua kazi inayofanya kazi iliyowasilishwa na mfanyakazi wako na bonyeza "Thibitisha na Maliza" ili kutolewa kwa fedha zilizowekwa kwenye amana.',
    milestone_go_dashboard: 'Nenda kwenye Dashibodi',
    corporate_blockage_title: 'Zuio la Hatua za Kazi za Kampuni',
    corporate_blockage_platform: 'Dhamana ya Uadilifu wa Kampuni ya LINEKORA',
    corporate_blockage_desc: 'Maelekezo ya usalama ya jukwaa yanahitaji makampuni kusasisha, kutathmini au kuthibitisha kazi zilizopo kabla ya kuchapisha orodha mpya.',
    corporate_resolve_hint: 'Tatua mara moja kwenye Dashibodi yako:',
    corporate_resolve_desc: 'Vinjari sehemu yako ya kampuni, chagua mkataba unaofanya kazi uliowasilishwa na mfanyakazi wako na bonyeza "Thibitisha na Maliza".',
    corporate_go_dashboard: 'Nenda kwenye Dashibodi ya Kampuni',
    active_contracts_title: 'Mikataba Hai na Uhamisho wa Hatua za Kazi',
    active_contracts_desc: 'Thibitisha hatua zilizokamilika, omba sasisho za maendeleo, au ukatae matatizo mara moja.',
    contract_active: 'Mkataba Hai',
    completion_requested: 'Ukamilishaji Umeombwa',
    in_progress_correction: 'Sahihisho Linaloendelea',
    arbitration_dispute: 'Mzozo wa Usuluhishi',
    finished_approved: 'Imekamilika na Imethibitishwa',
    flagged_untrusted: 'Imeashiriwa Kuwa Haiaminiwiki',
    approve_complete: 'Thibitisha na Maliza',
    need_adjustment: 'Inahitaji Sasisho',
    dispute: 'Mzozo',
    mark_untrusted: 'Weka Kuwa Haiaminiwiki',
    all_contracts_settled: 'Mikataba Yote Imekamilika',
    no_outstanding: 'Hakuna uhamisho uliobaki au bendera za ukamilishaji zinazosubiri.',
    file_worker_reputation: 'Hifadhi Sifa za Mfanyakazi',
    masterclass_standard: 'Viwango vya Juu (5/5)',
    highly_commended: 'Inapendekezwa Sana (4/5)',
    standard_alignment: 'Ulinganisho wa Kawaida (3/5)',
    needs_revision: 'Inahitaji Kurekebishwa (2/5)',
    flagged_poor: 'Kazi Mbaya Imeashiriwa (1/5)',
    submit_release_funds: 'Wasilisha na Kutolewa Fedha',
    disputed_milestone: 'Hatua ya kazi katika mzozo',
    milestone_dispute_log: 'Mzozo wa hatua ya kazi umeombwa. Mapitio ya usuluhishi yameanza.',
    milestone_returned: 'Hatua ya Kazi Imerejeshwa',
    perfect_execution: 'Ufanyaji kazi bora!',
    contract_approved: 'Mkataba Umethibitishwa na Kutumwa',
    milestone_approved_escrow: 'Hatua ya Kazi Imethibitishwa! Fedha zilizowekwa kwenye amana zimetolewa na ukadiriaji umehifadhiwa salama.',
    escalation_warning: 'Kuongezeka Kiotomatiki kwa Siku 3 za Ucheleweshaji',
    escalation_desc: 'Ukamilishaji huu uliwasilishwa siku 3 zilizopita. Kuokoa kwa jukwaa kunahitaji ukaguzi wa haraka.',
    milestone_secure_escrow: 'Amana Salama ya LINEKORA',
    milestone_secure_desc: 'Kazi hii inatumia dhamana za usalama wa hatua za kazi. Mshahara umewekwa kwenye hazina kabla ya kukamilika kwa hatua za kazi.',
    completion_requested_blocked: 'Ukamilishaji Umeombwa na Kuzuiwa',
    disputed_admin_audit: 'Katika Mzozo: Chini ya Ukaguzi wa Msimamizi',
    flagged_penalty: 'Imeashiriwa: Adhabu ya Kuwa Haiaminiwiki',
    request_completion: 'Omba Ukamilishaji',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('linekora_lang');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('linekora_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
